import 'package:h_food/models/category_model.dart';
import 'package:h_food/models/product_model.dart';

final List<ProductsModel> productMockup = [
  ProductsModel(
    id: 1,
    title: "Bakery 1",
    calories: 175,
    prices: [PriceItem("", 1.99)],
    options: [],
    description:
        "Lorem ipsum dolor sit amet. Qui minima inventore vel nisi laudantium ut accusantium beatae aut quas sint ab nulla beatae et dolor autem? Quo quibusdam iste qui reiciendis enim aut ipsum facere.",
    category: CategoryModel(id: 1),
    cookDuration: 0,
    discount: 0,
    featured: false,
    rate: 4.6,
    favoriteCount: 15,
    orderCount: 164,
    image: "assets/images/items/bakery1.jpg",
  ),
  ProductsModel(
    id: 2,
    title: "Bakery 2",
    calories: 185,
    prices: [PriceItem("", 2.99)],
    options: [],
    description:
        "Lorem ipsum dolor sit amet. Qui minima inventore vel nisi laudantium ut accusantium beatae aut quas sint ab nulla beatae et dolor autem? Quo quibusdam iste qui reiciendis enim aut ipsum facere.",
    category: CategoryModel(id: 1),
    cookDuration: 0,
    discount: 0,
    featured: false,
    image: "assets/images/items/bakery2.jpg",
    favoriteCount: 5,
    rate: 4.5,
    orderCount: 164,
  ),
  ProductsModel(
    id: 3,
    title: "Barbecue",
    calories: 1200,
    prices: [PriceItem("medium", 9.99), PriceItem("large", 15.99)],
    options: [
      OptionItem("Drink", ["coca cola", "sprite", "fanta", "pepsi"], false),
      OptionItem("Sauce", [
        "mayonnaise",
        "ketchup",
        "mexican sauce",
        "garlic pate",
      ], true),
      OptionItem("Fried sides", ["potato fried", "yam fried"], false),
    ],
    description:
        "Lorem ipsum dolor sit amet. Qui minima inventore vel nisi laudantium ut accusantium beatae aut quas sint ab nulla beatae et dolor autem? Quo quibusdam iste qui reiciendis enim aut ipsum facere.",
    category: CategoryModel(id: 2),
    cookDuration: 60,
    discount: 0,
    featured: true,
    image: "assets/images/items/barbecue1.jpg",
    favoriteCount: 12,
    rate: 4.6,
    orderCount: 188,
  ),
  ProductsModel(
    id: 4,
    title: "Burger 1",
    calories: 1400,
    prices: [
      PriceItem("small", 4.99),
      PriceItem("medium", 6.99),
      PriceItem("large", 8.99),
    ],
    options: [
      OptionItem("Sauce", [
        "mayonnaise",
        "ketchup",
        "mexican sauce",
        "garlic pate",
      ], true),
    ],
    description:
        "Lorem ipsum dolor sit amet. Qui minima inventore vel nisi laudantium ut accusantium beatae aut quas sint ab nulla beatae et dolor autem? Quo quibusdam iste qui reiciendis enim aut ipsum facere.",
    category: CategoryModel(id: 3),
    cookDuration: 25,
    discount: 0.1,
    featured: false,
    image: "assets/images/items/burger1.jpg",
    favoriteCount: 19,
    rate: 4.4,
    orderCount: 182,
  ),
  ProductsModel(
    id: 5,
    title: "Burger Menu S",
    calories: 2400,
    prices: [
      PriceItem("small", 6.99),
      PriceItem("medium", 7.99),
      PriceItem("large", 8.99),
    ],
    options: [
      OptionItem("Drink", ["coca cola", "sprite", "fanta", "pepsi"], false),
      OptionItem("Sauce", [
        "mayonnaise",
        "ketchup",
        "mexican sauce",
        "garlic pate",
      ], true),
      OptionItem("Fried sides", ["potato fried", "yam fried"], false),
    ],
    description:
        "Lorem ipsum dolor sit amet. Qui minima inventore vel nisi laudantium ut accusantium beatae aut quas sint ab nulla beatae et dolor autem? Quo quibusdam iste qui reiciendis enim aut ipsum facere.",
    category: CategoryModel(id: 3),
    cookDuration: 30,
    discount: 0,
    featured: true,
    image: "assets/images/items/burger2.jpg",
    favoriteCount: 3,
    rate: 4.5,
    orderCount: 107,
  ),
  ProductsModel(
    id: 6,
    title: "Full Burger",
    calories: 2400,
    prices: [PriceItem("medium", 8.99), PriceItem("large", 9.99)],
    options: [
      OptionItem("Sauce", [
        "mayonnaise",
        "ketchup",
        "mexican sauce",
        "garlic pate",
      ], true),
    ],
    description:
        "Lorem ipsum dolor sit amet. Qui minima inventore vel nisi laudantium ut accusantium beatae aut quas sint ab nulla beatae et dolor autem? Quo quibusdam iste qui reiciendis enim aut ipsum facere.",
    category: CategoryModel(id: 3),
    cookDuration: 30,
    discount: 0,
    featured: false,
    image: "assets/images/items/burger3.jpg",
    favoriteCount: 5,
    rate: 4.6,
    orderCount: 56,
  ),
  ProductsModel(
    id: 7,
    title: "Meat Burger",
    calories: 1800,
    prices: [PriceItem("medium", 7.99), PriceItem("large", 8.99)],
    options: [
      OptionItem("Sauce", [
        "mayonnaise",
        "ketchup",
        "mexican sauce",
        "garlic pate",
      ], true),
    ],
    description:
        "Lorem ipsum dolor sit amet. Qui minima inventore vel nisi laudantium ut accusantium beatae aut quas sint ab nulla beatae et dolor autem? Quo quibusdam iste qui reiciendis enim aut ipsum facere.",
    category: CategoryModel(id: 3),
    cookDuration: 30,
    discount: 0.25,
    featured: false,
    image: "assets/images/items/burger4.jpg",
    favoriteCount: 18,
    rate: 4.8,
    orderCount: 167,
  ),
  ProductsModel(
    id: 8,
    title: "Chicken 1",
    calories: 1750,
    prices: [PriceItem("half chicken", 2.99), PriceItem("Whole chicken", 3.99)],
    options: [
      OptionItem("Fried sides", ["potato fried", "yam fried"], false),
    ],
    description:
        "Lorem ipsum dolor sit amet. Qui minima inventore vel nisi laudantium ut accusantium beatae aut quas sint ab nulla beatae et dolor autem? Quo quibusdam iste qui reiciendis enim aut ipsum facere.",
    category: CategoryModel(id: 4),
    cookDuration: 20,
    discount: 0.25,
    featured: false,
    image: "assets/images/items/chicken1.jpg",
    favoriteCount: 15,
    rate: 4.4,
    orderCount: 195,
  ),
  ProductsModel(
    id: 9,
    title: "Chicken 2",
    calories: 2150,
    prices: [PriceItem("half chicken", 3.99), PriceItem("Whole chicken", 4.99)],
    options: [
      OptionItem("Fried sides", ["potato fried", "yam fried"], false),
    ],
    description:
        "Lorem ipsum dolor sit amet. Qui minima inventore vel nisi laudantium ut accusantium beatae aut quas sint ab nulla beatae et dolor autem? Quo quibusdam iste qui reiciendis enim aut ipsum facere.",
    category: CategoryModel(id: 4),
    cookDuration: 20,
    discount: 0,
    featured: false,
    image: "assets/images/items/chicken2.jpg",
    favoriteCount: 9,
    rate: 4.1,
    orderCount: 88,
  ),
  ProductsModel(
    id: 10,
    title: "Chicken 3",
    calories: 1950,
    prices: [PriceItem("half chicken", 3.99), PriceItem("Whole chicken", 4.99)],
    options: [
      OptionItem("Fried sides", ["potato fried", "yam fried"], false),
    ],
    description:
        "Lorem ipsum dolor sit amet. Qui minima inventore vel nisi laudantium ut accusantium beatae aut quas sint ab nulla beatae et dolor autem? Quo quibusdam iste qui reiciendis enim aut ipsum facere.",
    category: CategoryModel(id: 4),
    cookDuration: 25,
    discount: 0,
    featured: false,
    image: "assets/images/items/chicken3.jpg",
    favoriteCount: 11,
    rate: 4.7,
    orderCount: 126,
  ),
  ProductsModel(
    id: 11,
    title: "Chinese Food 1",
    calories: 900,
    prices: [PriceItem("", 2.99)],
    options: [],
    description:
        "Lorem ipsum dolor sit amet. Qui minima inventore vel nisi laudantium ut accusantium beatae aut quas sint ab nulla beatae et dolor autem? Quo quibusdam iste qui reiciendis enim aut ipsum facere.",
    category: CategoryModel(id: 5),
    cookDuration: 30,
    discount: 0,
    featured: false,
    image: "assets/images/items/chinese1.jpg",
    favoriteCount: 5,
    rate: 4.8,
    orderCount: 53,
  ),
  ProductsModel(
    id: 12,
    title: "Chinese Food 2",
    calories: 950,
    prices: [PriceItem("", 3.99)],
    options: [],
    description:
        "Lorem ipsum dolor sit amet. Qui minima inventore vel nisi laudantium ut accusantium beatae aut quas sint ab nulla beatae et dolor autem? Quo quibusdam iste qui reiciendis enim aut ipsum facere.",
    category: CategoryModel(id: 5),
    cookDuration: 30,
    discount: 0,
    featured: false,
    image: "assets/images/items/chinese2.jpg",
    favoriteCount: 8,
    rate: 4.2,
    orderCount: 70,
  ),
  ProductsModel(
    id: 13,
    title: "Chinese Food 3",
    calories: 900,
    prices: [PriceItem("", 5.99)],
    options: [],
    description:
        "Lorem ipsum dolor sit amet. Qui minima inventore vel nisi laudantium ut accusantium beatae aut quas sint ab nulla beatae et dolor autem? Quo quibusdam iste qui reiciendis enim aut ipsum facere.",
    category: CategoryModel(id: 5),
    cookDuration: 45,
    discount: 0,
    featured: false,
    image: "assets/images/items/chinese3.jpg",
    favoriteCount: 16,
    rate: 4.5,
    orderCount: 100,
  ),
  ProductsModel(
    id: 14,
    title: "Chinese Food 4",
    calories: 900,
    prices: [PriceItem("", 1.99)],
    options: [],
    description:
        "Lorem ipsum dolor sit amet. Qui minima inventore vel nisi laudantium ut accusantium beatae aut quas sint ab nulla beatae et dolor autem? Quo quibusdam iste qui reiciendis enim aut ipsum facere.",
    category: CategoryModel(id: 5),
    cookDuration: 30,
    discount: 0,
    featured: false,
    image: "assets/images/items/chinese4.jpg",
    favoriteCount: 16,
    rate: 4.5,
    orderCount: 100,
  ),
  ProductsModel(
    id: 15,
    title: "Coffee A",
    calories: 20,
    prices: [PriceItem("25 cl", 0.99), PriceItem("35 cl", 1.99)],
    options: [
      OptionItem("Recipe", ["Simple", "Cream"], false),
      OptionItem("Sugar ?", ["No", "Yes"], false),
    ],
    description:
        "Lorem ipsum dolor sit amet. Qui minima inventore vel nisi laudantium ut accusantium beatae aut quas sint ab nulla beatae et dolor autem? Quo quibusdam iste qui reiciendis enim aut ipsum facere.",
    category: CategoryModel(id: 6),
    cookDuration: 5,
    discount: 0,
    featured: false,
    image: "assets/images/items/coffee1.jpg",
    favoriteCount: 13,
    rate: 4.7,
    orderCount: 188,
  ),
  ProductsModel(
    id: 16,
    title: "Coffee B",
    calories: 30,
    prices: [PriceItem("33 cl", 0.99), PriceItem("50 cl", 1.99)],
    options: [
      OptionItem("Recipe", ["Simple", "Cream"], false),
      OptionItem("Sugar ?", ["No", "Yes"], false),
    ],
    description:
        "Lorem ipsum dolor sit amet. Qui minima inventore vel nisi laudantium ut accusantium beatae aut quas sint ab nulla beatae et dolor autem? Quo quibusdam iste qui reiciendis enim aut ipsum facere.",
    category: CategoryModel(id: 6),
    cookDuration: 5,
    discount: 0,
    featured: false,
    image: "assets/images/items/coffee2.jpg",
    favoriteCount: 17,
    rate: 4.2,
    orderCount: 178,
  ),
  ProductsModel(
    id: 17,
    title: "Pancakes",
    calories: 450,
    prices: [PriceItem("", 2.99)],
    options: [
      OptionItem("Chocolate", ["Nutella", "Choco Quick", "ChocoMilk"], false),
      OptionItem("Sugar", ["No sugar", "Honey", "sugar"], false),
    ],
    description:
        "Lorem ipsum dolor sit amet. Qui minima inventore vel nisi laudantium ut accusantium beatae aut quas sint ab nulla beatae et dolor autem? Quo quibusdam iste qui reiciendis enim aut ipsum facere.",
    category: CategoryModel(id: 7),
    cookDuration: 15,
    discount: 0,
    featured: false,
    image: "assets/images/items/dessert1.jpg",
    favoriteCount: 11,
    rate: 4.4,
    orderCount: 115,
  ),
  ProductsModel(
    id: 18,
    title: "Dessert",
    calories: 850,
    prices: [PriceItem("", 3.99)],
    options: [],
    description:
        "Lorem ipsum dolor sit amet. Qui minima inventore vel nisi laudantium ut accusantium beatae aut quas sint ab nulla beatae et dolor autem? Quo quibusdam iste qui reiciendis enim aut ipsum facere.",
    category: CategoryModel(id: 7),
    cookDuration: 15,
    discount: 0,
    featured: false,
    image: "assets/images/items/dessert2.jpg",
    favoriteCount: 20,
    rate: 4.2,
    orderCount: 126,
  ),
  ProductsModel(
    id: 19,
    title: "Limonade",
    calories: 80,
    prices: [PriceItem("", 4.99)],
    options: [
      OptionItem("Sugar", [
        "No sugar",
        "1 Stick",
        "2 Sticks",
        "3 Sticks",
      ], false),
    ],
    description:
        "Lorem ipsum dolor sit amet. Qui minima inventore vel nisi laudantium ut accusantium beatae aut quas sint ab nulla beatae et dolor autem? Quo quibusdam iste qui reiciendis enim aut ipsum facere.",
    category: CategoryModel(id: 8),
    cookDuration: 0,
    discount: 0,
    featured: false,
    image: "assets/images/items/drinks1.jpg",
    favoriteCount: 20,
    rate: 4.2,
    orderCount: 126,
  ),
  ProductsModel(
    id: 20,
    title: "Pepsi",
    calories: 160,
    prices: [PriceItem("33 cl", 0.99), PriceItem("50 cl", 1.99)],
    options: [],
    description:
        "Lorem ipsum dolor sit amet. Qui minima inventore vel nisi laudantium ut accusantium beatae aut quas sint ab nulla beatae et dolor autem? Quo quibusdam iste qui reiciendis enim aut ipsum facere.",
    category: CategoryModel(id: 8),
    cookDuration: 10,
    discount: 0,
    featured: false,
    image: "assets/images/items/drinks2.jpg",
    favoriteCount: 5,
    rate: 4.7,
    orderCount: 346,
  ),
  ProductsModel(
    id: 21,
    title: "Potato Fried",
    calories: 600,
    prices: [
      PriceItem("250 g", 0.99),
      PriceItem("500 g", 1.89),
      PriceItem("700 g", 2.5),
    ],
    options: [],
    description:
        "Lorem ipsum dolor sit amet. Qui minima inventore vel nisi laudantium ut accusantium beatae aut quas sint ab nulla beatae et dolor autem? Quo quibusdam iste qui reiciendis enim aut ipsum facere.",
    category: CategoryModel(id: 9),
    cookDuration: 10,
    discount: 0,
    featured: true,
    image: "assets/images/items/fried1.jpg",
    favoriteCount: 28,
    rate: 4.8,
    orderCount: 241,
  ),
  ProductsModel(
    id: 22,
    title: "Hot Dog 1",
    calories: 1100,
    prices: [PriceItem("", 1)],
    options: [
      OptionItem("Sauce", [
        "mayonnaise",
        "ketchup",
        "mexican sauce",
        "garlic pate",
      ], true),
    ],
    description:
        "Lorem ipsum dolor sit amet. Qui minima inventore vel nisi laudantium ut accusantium beatae aut quas sint ab nulla beatae et dolor autem? Quo quibusdam iste qui reiciendis enim aut ipsum facere.",
    category: CategoryModel(id: 10),
    cookDuration: 15,
    discount: 0,
    featured: true,
    image: "assets/images/items/hotdog1.jpg",
    favoriteCount: 21,
    rate: 4.3,
    orderCount: 193,
  ),
  ProductsModel(
    id: 23,
    title: "Hot Dog Max",
    calories: 1100,
    prices: [PriceItem("", 1.29)],
    options: [
      OptionItem("Sauce", [
        "mayonnaise",
        "ketchup",
        "mexican sauce",
        "garlic pate",
      ], true),
    ],
    description:
        "Lorem ipsum dolor sit amet. Qui minima inventore vel nisi laudantium ut accusantium beatae aut quas sint ab nulla beatae et dolor autem? Quo quibusdam iste qui reiciendis enim aut ipsum facere.",
    category: CategoryModel(id: 10),
    cookDuration: 15,
    discount: 0,
    featured: false,
    image: "assets/images/items/hotdog2.jpg",
    favoriteCount: 23,
    rate: 4.4,
    orderCount: 203,
  ),
  ProductsModel(
    id: 24,
    title: "Pasta 1",
    calories: 750,
    prices: [PriceItem("", 2.49)],
    options: [],
    description:
        "Lorem ipsum dolor sit amet. Qui minima inventore vel nisi laudantium ut accusantium beatae aut quas sint ab nulla beatae et dolor autem? Quo quibusdam iste qui reiciendis enim aut ipsum facere.",
    category: CategoryModel(id: 11),
    cookDuration: 25,
    discount: 0,
    featured: false,
    image: "assets/images/items/pasta1.jpg",
    favoriteCount: 23,
    rate: 4.7,
    orderCount: 93,
  ),
  ProductsModel(
    id: 25,
    title: "Pasta 2",
    calories: 750,
    prices: [PriceItem("", 2.59)],
    options: [],
    description:
        "Lorem ipsum dolor sit amet. Qui minima inventore vel nisi laudantium ut accusantium beatae aut quas sint ab nulla beatae et dolor autem? Quo quibusdam iste qui reiciendis enim aut ipsum facere.",
    category: CategoryModel(id: 11),
    cookDuration: 20,
    discount: 0,
    featured: false,
    image: "assets/images/items/pasta2.jpg",
    favoriteCount: 7,
    rate: 4.7,
    orderCount: 93,
  ),
  ProductsModel(
    id: 26,
    title: "Silver Pizza",
    calories: 1100,
    prices: [
      PriceItem("small", 5.99),
      PriceItem("medium", 6.99),
      PriceItem("large", 7.99),
    ],
    options: [
      OptionItem("Sauce", [
        "mayonnaise",
        "ketchup",
        "mexican sauce",
        "garlic pate",
      ], true),
    ],
    description:
        "Lorem ipsum dolor sit amet. Qui minima inventore vel nisi laudantium ut accusantium beatae aut quas sint ab nulla beatae et dolor autem? Quo quibusdam iste qui reiciendis enim aut ipsum facere.",
    category: CategoryModel(id: 12),
    cookDuration: 45,
    discount: 0,
    featured: false,
    image: "assets/images/items/pizza1.jpg",
    favoriteCount: 7,
    rate: 4.4,
    orderCount: 82,
  ),
  ProductsModel(
    id: 27,
    title: "Golden Pizza",
    calories: 1000,
    prices: [
      PriceItem("small", 6),
      PriceItem("medium", 7),
      PriceItem("large", 8),
    ],
    options: [
      OptionItem("Sauce", [
        "mayonnaise",
        "ketchup",
        "mexican sauce",
        "garlic pate",
      ], true),
    ],
    description:
        "Lorem ipsum dolor sit amet. Qui minima inventore vel nisi laudantium ut accusantium beatae aut quas sint ab nulla beatae et dolor autem? Quo quibusdam iste qui reiciendis enim aut ipsum facere.",
    category: CategoryModel(id: 12),
    cookDuration: 45,
    discount: 0.2,
    featured: true,
    image: "assets/images/items/pizza2.jpg",
    favoriteCount: 7,
    rate: 4.7,
    orderCount: 147,
  ),
  ProductsModel(
    id: 28,
    title: "Pizza S",
    calories: 1250,
    prices: [
      PriceItem("small", 5.99),
      PriceItem("medium", 6.99),
      PriceItem("large", 7.99),
    ],
    options: [
      OptionItem("Sauce", [
        "mayonnaise",
        "ketchup",
        "mexican sauce",
        "garlic pate",
      ], true),
    ],
    description:
        "Lorem ipsum dolor sit amet. Qui minima inventore vel nisi laudantium ut accusantium beatae aut quas sint ab nulla beatae et dolor autem? Quo quibusdam iste qui reiciendis enim aut ipsum facere.",
    category: CategoryModel(id: 12),
    cookDuration: 45,
    discount: 0.2,
    featured: true,
    image: "assets/images/items/pizza3.jpg",
    favoriteCount: 11,
    rate: 4.7,
    orderCount: 197,
  ),
  ProductsModel(
    id: 29,
    title: "Pizza X",
    calories: 1150,
    prices: [
      PriceItem("small", 5.5),
      PriceItem("medium", 6.5),
      PriceItem("large", 7.5),
    ],
    options: [
      OptionItem("Sauce", [
        "mayonnaise",
        "ketchup",
        "mexican sauce",
        "garlic pate",
      ], true),
    ],
    description:
        "Lorem ipsum dolor sit amet. Qui minima inventore vel nisi laudantium ut accusantium beatae aut quas sint ab nulla beatae et dolor autem? Quo quibusdam iste qui reiciendis enim aut ipsum facere.",
    category: CategoryModel(id: 12),
    cookDuration: 40,
    discount: 0,
    featured: false,
    image: "assets/images/items/pizza4.jpg",
    favoriteCount: 7,
    rate: 4.3,
    orderCount: 127,
  ),
  ProductsModel(
    id: 30,
    title: "Sandwich A",
    calories: 850,
    prices: [PriceItem("small", 0.79), PriceItem("medium", 0.99)],
    options: [
      OptionItem("Sauce", [
        "mayonnaise",
        "ketchup",
        "mexican sauce",
        "garlic pate",
      ], true),
    ],
    description:
        "Lorem ipsum dolor sit amet. Qui minima inventore vel nisi laudantium ut accusantium beatae aut quas sint ab nulla beatae et dolor autem? Quo quibusdam iste qui reiciendis enim aut ipsum facere.",
    category: CategoryModel(id: 13),
    cookDuration: 10,
    discount: 0,
    featured: false,
    image: "assets/images/items/sandwich1.jpg",
    favoriteCount: 7,
    rate: 4.3,
    orderCount: 207,
  ),
  ProductsModel(
    id: 31,
    title: "Sandwich S",
    calories: 950,
    prices: [PriceItem("small", 0.89), PriceItem("medium", 1.19)],
    options: [
      OptionItem("Sauce", [
        "mayonnaise",
        "ketchup",
        "mexican sauce",
        "garlic pate",
      ], true),
    ],
    description:
        "Lorem ipsum dolor sit amet. Qui minima inventore vel nisi laudantium ut accusantium beatae aut quas sint ab nulla beatae et dolor autem? Quo quibusdam iste qui reiciendis enim aut ipsum facere.",
    category: CategoryModel(id: 13),
    cookDuration: 10,
    discount: 0,
    featured: false,
    image: "assets/images/items/sandwich2.jpg",
    favoriteCount: 19,
    rate: 4.8,
    orderCount: 217,
  ),
  ProductsModel(
    id: 32,
    title: "Vegan Food A",
    calories: 300,
    prices: [PriceItem("", 3)],
    options: [],
    description:
        "Lorem ipsum dolor sit amet. Qui minima inventore vel nisi laudantium ut accusantium beatae aut quas sint ab nulla beatae et dolor autem? Quo quibusdam iste qui reiciendis enim aut ipsum facere.",
    category: CategoryModel(id: 14),
    cookDuration: 10,
    discount: 0,
    featured: false,
    image: "assets/images/items/vegan1.jpg",
    favoriteCount: 7,
    rate: 4.8,
    orderCount: 23,
  ),
  ProductsModel(
    id: 33,
    title: "Vegan Food B",
    calories: 300,
    prices: [PriceItem("", 3.5)],
    options: [],
    description:
        "Lorem ipsum dolor sit amet. Qui minima inventore vel nisi laudantium ut accusantium beatae aut quas sint ab nulla beatae et dolor autem? Quo quibusdam iste qui reiciendis enim aut ipsum facere.",
    category: CategoryModel(id: 14),
    cookDuration: 15,
    discount: 0,
    featured: false,
    image: "assets/images/items/vegan2.jpg",
    favoriteCount: 7,
    rate: 4.3,
    orderCount: 33,
  ),
  ProductsModel(
    id: 34,
    title: "Vegan Food S",
    calories: 300,
    prices: [PriceItem("", 3.5)],
    options: [],
    description:
        "Lorem ipsum dolor sit amet. Qui minima inventore vel nisi laudantium ut accusantium beatae aut quas sint ab nulla beatae et dolor autem? Quo quibusdam iste qui reiciendis enim aut ipsum facere.",
    category: CategoryModel(id: 14),
    cookDuration: 20,
    discount: 0,
    featured: false,
    image: "assets/images/items/vegan3.jpg",
    favoriteCount: 3,
    rate: 4.2,
    orderCount: 23,
  ),
];
